//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int ID { get; set; }
        public Nullable<int> Availbility { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Genre { get; set; }
        public Nullable<int> Year { get; set; }
        public string Status { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    }
}
